### Qery Users
GET localhost:3000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjY1YTk2OGM3NjRjMzRkZGU0ZTJlNWQiLCJpYXQiOjE3MTgyMTA5NTIsImV4cCI6MTcxODIxMjc1MiwidHlwZSI6IkFDQ0VTUyJ9.lmKrMNTVTMVpUS5-D7k1XBUyZJK7_BZvPRslO4AmsBg

### Get User